### ISSUE TITLE
Донастроить max-nesting-depth

### ISSUE THREAD

**Issue by a-seredkin** [htmlacademy/stylelint-config-htmlacademy#14]
На before ошибка `expected nesting depth to be no more then 2` протестую. Тут нет вложенности селектора больше 2х. max-nesting-depth надо перенастраивать. 
![image](https://user-images.githubusercontent.com/79633923/133237886-c4c0de98-eefb-42aa-8fcc-d7d2bbd183ec.png)

**Comment by captain-zsa** [comment]
Также проблема с реальной вложенностью > 2 уже не определяется.
```
.form__users {
  margin-top: 43px;

  @media (min-width: $tablet-width) {
    display: flex;
    align-items: flex-start;
  }

  .form__field {
    margin-bottom: 22px;

    @media (min-width: $tablet-width) {
      margin-bottom: 18px;
    }

    @media (min-width: $desktop-width) {
      width: 80%;
    }

    span { // тут 3, а тест не видит этого
      @media (min-width: $tablet-width) {
        margin-right: 26px;
      }
    }
  }
}
```

**Comment by firefoxic** [comment]
У меня для вас есть три новости: 2 плохих и 1 хорошая.

1. Запрос в этой ишье не совсем корректный и настроить это указанным правилом не представляется возможным
2. Я кажется нашёл, как настроить то, что нам действительно нужно!
3. Но вам эта находка не понравится 🤣

**Comment by firefoxic** [comment]
В общем дело такое. Правило `max-nesting-depth` вообще не про то, что мы от него хотим. Оно как раз про вложенность блоков кода (фигурных скобок) друг в друга. Мало того, оно ещё и с `"ignoreAtRules": ["media"]` работает либо задуманно топорно, либо это баг, но если с этим игнором `@media` вложить во что-то, то в этот `@media` можно будет вкладывать вообще всё что угодно с любой вложенностью, стайллинт просто всё содержимое этого `@media` пропускает. То есть это совсем не так же работает, как `"ignore": ["pseudo-classes"]`, с которым игнорируется только сам псевдокласс, а вложенное в него плюсуется к предыдущей вложенности.
Ну и вишенкой на торте: если `.b` вложить в `.a`
```scss
.a {
	.b {
		// …
	}
}
```
то глубина вложенности = 1, а не 2. Именно поэтому в примере от @captain-zsa не детектится `span` как лишний уровень вложенности — он второй :)

Теперь про то, что мы хотим — ограничить сложность составных селекторов. А это совсем другое правило — [selector-max-compound-selectors](https://stylelint.io/user-guide/rules/selector-max-compound-selectors/). Вот в нём как раз 2 означает ровно то, что мы хотим (в результирующем коде):

```scss
.a .b {
	/* … */
}
```

Вот только опять есть нюансик — сиблинги тут никак не настраиваются, любая коминаторика простых селекторов в сложный приравнивается к добавлению уровня сложного селектора. Так что что-то типа такого:

```scss
.a:hover + .b > .с {
	color: red;
}
```
под двоечку уже не пролезает. С другой стороны, лично я никогда не понимал, какого чёрта по кодгайду академии можно сиблингами хоть до смерти обмазываться. Тем более сейчас, когда у нас есть кастомки.

Вердикт (от меня) таков: могу запулреквестить то, во что хорошо вписывается мой пример максимально возможных и достаточных вложеенностей, которые для себя когда-то, а теперь и для своих студентов соорудил как пример того, в каком порядке нужно друг в друга разные типы селекторов/правил вкладывать, чтобы самим потом не запутаться в своём же коде. И настройка конфига будет при этом соответствовать двум уровням максимальной сложносоставности селекторов и двум уровням максимальной глубине вложенности (с нормальным игнором псевдоклассов и безблочных at-правил). Но с такой настройкой некоторые задачи не решить без кастомок. Для меня не проблема, я то как раз учу студенто упрощать сложность селекторов, вложенностей и вообще кода с помощью кастомок, но у курсов по вёрстке в этом месте зияющая пустота и не знаю, как её авторам заполнять.

**Comment by firefoxic** [comment]
## Nesting

Вложенность (одних блоков стилевого кода в другие) — это не только препроцессорная фича, скоро она будет доступна в браузерах — есть спека и даже активно ведутся работы по внедрению в браузеры. Но браузерный нестинг будет отличаться от препроцессорного. Соответствовать спеке стремится плагин postcss-nesting, но тоже вряд ли удаётся полностью.

Пока что мы используем возможность нестинга из Sass. Но используем абы-как, без системы и беспорядочно. А порядок и система тут важны, и не только для единообразия, хотя оно и важно для зачёта критерия.

Проще всего наводить порядок в нестинге, расставив приоритет разным блокам стилевого кода, и в соответствии с ним сортируя их, выставляя *друг за другом* и *друг в друге*:

1. **все** общие свойства самой сущности
2. `@media` только со свойствами самой сущности
3. `&:pseudo-classes`, как динамические модификаторы
4. `&--bem_modifiers`
5. `&:pseudo-elements`

В псевдо-классы и бэм-модификаторы можно вкладывать другие модификаторы, но только предыдущее по списку:

- в `&:pseudo-classes` → `@media`.
- в `&--bem_modifiers` → `@media` и `&:pseudo-classes`, внутрь которых тоже можно вложить `@media`.

А вот с псевдо-элементами всё чуть сложнее. Нам нужно их записывать после псевдо-классов, и только `@media` можем вложить и то не желательно. И если изменений много, то один псевдик может сильно раздербаниться по всему коду, который станет сильно нечитабельным. Это можно избежать при помощи кастомных свойств, если вынести в них все изменяемые в псевдике значения. Тогда можно во всех модификациях изменять кастомные свойства у самой бэм-сущности, а псевдик описать только один раз в конце, после всего остального кода. Любое изменение кастомного свойства скажется на псевдике, а нам не придётся бегать по всей портянке кода в поисках фрагментов кода псевдика.

Вот пример всех возможных допустимых по этой методике многоуровневой вложенности с верной последовательностью:

```scss
.block {
	--fill: orange;
	--size: 20px;

	padding: 4px;
	aspect-ratio: 1;
	width: var(--size);
	background: var(--fill);

	@media #{$not-mobile} {
		--size: 24px;
	}

	&:hover {
		--fill: orangered;

		@media #{$not-mobile} {
			--fill: gold;
		}
	}

	&--mod-name_mod-value {
		--fill: deepskyblue;

		@media #{$not-mobile} {
			--size: 32px;
		}

		&:hover {
			--fill: steelblue;

			@media #{$not-mobile} {
				--fill: blueviolet;
			}
		}
	}

	&::before {
		content: "";
		width: var(--size);
		aspect-ratio: 1;
		border-radius: 100%;
		background: var(--fill);
		filter: invert(1);
	}
}
```
