### ISSUE TITLE
Правило: проверять наличие цвета у фонового изображения

### ISSUE THREAD

**Issue by nikolai-shabalin** [htmlacademy/stylelint-config-htmlacademy#147]
```css
body {
  background-color: #000000;
  background-image: url("../images/background-body.jpg");
}
```

значение цвета проверять не нужно. Контрастность проверять другим правилом, если потребуется
