### ISSUE TITLE
Правило: lightness-notation

### ISSUE THREAD

**Issue by nikolai-shabalin** [htmlacademy/stylelint-config-htmlacademy#65]
Добавить правило [lightness-notation](https://stylelint.io/user-guide/rules/lightness-notation) со значением `percentage`: 

```js
'lightness-notation': 'percentage'
```

Это правило поддерживает функции `oklch`, `oklab` и `lch`, `lab`.

## "percentage"
Светловсть всегда должна выражаться в процентах.

Следующие шаблоны считаются проблемными:
```css
a { color: oklch(0.85 0.17 88) }

a { color: oklab(0.86 0.2 154) }

a { color: lch(85 0.17 88) }

a { color: lab(86 0.2 154) }
```

Следующие шаблоны **не** считаются проблемами:
```css
a { color: oklch(85% 0.17 88) }

a { color: oklab(86% 0.2 154) }

a { color: lch(85% 0.17 88) }

a { color: lab(86% 0.2 154) }
```
